### ISSUE TITLE
[FeatureReqest] Add logrotation

### ISSUE THREAD

**Issue by MegaV0lt** [blacksenator/fbcallrouter#15]
https://github.com/blacksenator/fbcallrouter/blob/18899565f8df101978684d879748c3b3a2a5618d/config.example.php#L25

Please add a simple logrotation to logfile. For example add a parameter `MaxLogSize=`
Rotate the log by simple move the log to *.prev when MaxLogSize is reached. Check can be done daily or so

**Comment by blacksenator** [comment]
First of all, thank you for your contribution and indorsement to my work. I appreciate that! As discussed [in the thread at the IP Phone Forum, there are such tools in Linux](https://www.ip-phone-forum.de/threads/fbcallrouter-logspam-oder-normal.315405/post-2516795). An extension of the logging to that effect will therefore not take place. This also against the background that the logging was only rudimentary in order to be able to better track the behavior of a 24/7 service in the background and to detect errors in development. Finally, it is also the case that the FRITZ!Box logs essential information much more conveniently with the call list.

**Comment by MegaV0lt** [comment]
You ma yadd an sample logrotate file for nwe users. e. g in contrib folder or in documentation...
```
/home/darkwing/fbcallrouter/callrouter_logging.txt {
	monthly
	rotate 1
	compress
	missingok
	notifempty
	create 644 darkwing darkwing
}
```
