### ISSUE TITLE
Phonebook entries are being added each incoming call

### ISSUE THREAD

**Issue by ihavenoface** [blacksenator/fbcallrouter#6]
No matter if the incoming number has already been added or not, it's getting added again.
Is this intended?

**Comment by blacksenator** [comment]
I have already observed that - but have not yet investigated it in more detail, because:
if the number was entered in the spam telephone book for the first time, then this should actually mean that the next call from this number is blocked in the FRITZ!Box immediately.
So the tool shouldn't have noticed anything about the blocked call, because it only reacts on types "RING". But I will investigate that more closely whether the call monitor also outputs blocked callers.

**Comment by blacksenator** [comment]
@ihavenoface
I have changed the code: before the entry in the blacklist it is checked whether this number is already available. After the entry, the blacklist will be reloaded
